version: "3.7"
services:

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpmvcmoha

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8081:80
    depends_on:
      - mariadb

  php:
    build: .
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html

